# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-05 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_add_surveys_permissions_to_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='molosurveypage',
            name='display_survey_directly',
            field=models.BooleanField(default=False, help_text=b'This is similar to polls, in which the questions are displayed directly on the page, instead of displaying a link to another page to complete the survey.', verbose_name=b'Display Question Directly'),
        ),
    ]
