# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-11 13:10
from __future__ import unicode_literals

from django.db import migrations
import molo.surveys.blocks
import wagtail.wagtailcore.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_add_streamfield_for_skip_logic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='molosurveyformfield',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='personalisablesurveyformfield',
            options={'ordering': ['sort_order'], 'verbose_name': 'personalisable form field'},
        ),
        migrations.AlterField(
            model_name='molosurveyformfield',
            name='skip_logic',
            field=molo.surveys.blocks.SkipLogicField([(b'skip_logic', wagtail.wagtailcore.blocks.StructBlock([(b'choice', wagtail.wagtailcore.blocks.CharBlock()), (b'skip_logic', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(b'next', b'Next default question'), (b'end', b'End of survey'), (b'question', b'Another question'), (b'survey', b'Another survey')])), (b'survey', wagtail.wagtailcore.blocks.PageChooserBlock(required=False, target_model='surveys.MoloSurveyPage')), (b'question', molo.surveys.blocks.QuestionSelectBlock(help_text=b'Please save the survey as a draft to populate or update the list of questions.', required=False))]))], blank=True, verbose_name=b'Answer options'),
        ),
        migrations.AlterField(
            model_name='personalisablesurveyformfield',
            name='skip_logic',
            field=molo.surveys.blocks.SkipLogicField([(b'skip_logic', wagtail.wagtailcore.blocks.StructBlock([(b'choice', wagtail.wagtailcore.blocks.CharBlock()), (b'skip_logic', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(b'next', b'Next default question'), (b'end', b'End of survey'), (b'question', b'Another question'), (b'survey', b'Another survey')])), (b'survey', wagtail.wagtailcore.blocks.PageChooserBlock(required=False, target_model='surveys.MoloSurveyPage')), (b'question', molo.surveys.blocks.QuestionSelectBlock(help_text=b'Please save the survey as a draft to populate or update the list of questions.', required=False))]))], blank=True, verbose_name=b'Answer options'),
        ),
    ]
