# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-30 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0014_make_count_positive_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='molosurveyformfield',
            name='admin_label',
            field=models.CharField(default=b'', help_text='Column header used during CSV export of survey responses.', max_length=256),
        ),
        migrations.AddField(
            model_name='personalisablesurveyformfield',
            name='admin_label',
            field=models.CharField(default=b'', help_text='Column header used during CSV export of survey responses.', max_length=256),
        ),
    ]
