# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-31 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0015_add_choices_to_skip_logic'),
    ]

    operations = [
        migrations.AddField(
            model_name='molosurveyformfield',
            name='page_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalisablesurveyformfield',
            name='page_break',
            field=models.BooleanField(default=False),
        ),
    ]
