# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-16 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_articletagrule'),
        ('surveys', '0015_add_choices_to_skip_logic'),
    ]

    operations = [
    ]
