# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-26 18:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_segmentusergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembershiprule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.SegmentUserGroup'),
        ),
        migrations.AlterField(
            model_name='segmentusergroup',
            name='users',
            field=models.ManyToManyField(related_name='segment_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
