# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-22 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0021_surveyresponserule'),
    ]

    operations = [
        migrations.AddField(
            model_name='molosurveyformfield',
            name='page_break',
            field=models.BooleanField(default=False, help_text='Inserts a page break which puts the next question onto a new page'),
        ),
        migrations.AddField(
            model_name='personalisablesurveyformfield',
            name='page_break',
            field=models.BooleanField(default=False, help_text='Inserts a page break which puts the next question onto a new page'),
        ),
    ]
